[project]
name = "webants"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "charset-normalizer>=3.4.1",
    "cssselect>=1.3.0",
    "httpx>=0.28.1",
    "lxml>=5.3.0",
    "multidict>=6.1.0",
    "playwright>=1.51.0",
    "setuptools>=75.6.0",
    "ujson>=5.10.0",
]

[dependency-groups]
dev = [
    "ipython>=9.0.2",
    "pip>=24.3.1",
]
